Modelsの作成
nakainu/training-todo pull request #10
Opened 2020-04-21 02:30 UTC by nakainu

モデルの作成とマイグレーションファイルの作成、データベースへの適用を追加しました。

DB設計
```
userテーブルはユーザー情報を持つ
user {
    'username',	CharField("トレーニング名", max_length=50)
    'email',		EmailField("パスワード", max_length=255)
    'password',	CharField("メールアドレス", max_length=50)
}

todo {
    'title',	CharField("トレーニング名", max_length=50)
    'times,	PositiveIntegerField("回数")
    'done',	TBooleanField("status", default=False)
    'user',	ForeignKey("User", on_delete=models.CASCADE)
}
```

2020-04-21 02:48 UTC, shimizukawa requested changes
レビューしました

2020-04-21 02:48 UTC, shimizukawa commented on todo/models.py
> +class User(models.Model):
MUST: Django組み込みのユーザーモデルを使用して下さい。またその場合はTodoモデルの実装とは別に、「ログイン機能の実装」というPRでレビュー依頼を出して下さい。

以下のドキュメントが参考になります。

* https://docs.djangoproject.com/ja/3.0/topics/auth/

把握して動作するまで、1~2時間くらいかかるかもしれませんが、独自にUserモデルを用意してログイン画面実装等を進めるより早く終わると思います。

2020-04-21 02:48 UTC, shimizukawa commented on todo/models.py
> +    email = models.EmailField("パスワード", max_length=255)
nits: パスワード、ではなさそう 😕

2020-04-21 02:48 UTC, shimizukawa commented on todo/models.py
> +    done = models.BooleanField("status", default=False)
SHOULD: bool値を持たせるのであれば、代わりに完了日時を持たせる方法をお勧めします。
```
complete_at = models.DateTime('完了日時', null=True)
```

参考: 自走プログラマー:  53 「ブール値でなく日時にする」

2020-04-21 03:05 UTC, shimizukawa commented
@nakainu このPRを見る前に、認証の実装をしたほうがよさそうです。
Todoモデルはユーザーモデルに関連持ちますよね。

このPRの差分はmigrationファイルを除けばTodoモデルの15行くらいなので、このPRは捨てて、認証実装のPR後に実装するのがよさそうです。

2020-04-22 06:58 UTC, nakainu commented on todo/models.py
> +from django.contrib.auth import get_user_model
Userモデルを呼び出したいので、get_user_model()を呼び出す

2020-04-22 06:59 UTC, nakainu commented on todo/models.py
> +    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
TodoモデルとUserモデルを紐付ける

2020-04-22 07:06 UTC, shimizukawa approved these changes
LGTM!!

2020-04-22 07:10 UTC, merged